/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlLoginRouteImport } from './routes/control.login'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedControlRouteRouteImport } from './routes/_authenticated/control/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedControlIndexRouteImport } from './routes/_authenticated/control/index'
import { Route as AuthenticatedControlCasesIndexRouteImport } from './routes/_authenticated/control/cases/index'
import { Route as AuthenticatedControlCasesIdRouteImport } from './routes/_authenticated/control/cases/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlLoginRoute = ControlLoginRouteImport.update({
  id: '/control/login',
  path: '/control/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlRouteRoute =
  AuthenticatedControlRouteRouteImport.update({
    id: '/control',
    path: '/control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedControlIndexRoute =
  AuthenticatedControlIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedControlRouteRoute,
  } as any)
const AuthenticatedControlCasesIndexRoute =
  AuthenticatedControlCasesIndexRouteImport.update({
    id: '/cases/',
    path: '/cases/',
    getParentRoute: () => AuthenticatedControlRouteRoute,
  } as any)
const AuthenticatedControlCasesIdRoute =
  AuthenticatedControlCasesIdRouteImport.update({
    id: '/cases/$id',
    path: '/cases/$id',
    getParentRoute: () => AuthenticatedControlRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/control': typeof AuthenticatedControlRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/control/login': typeof ControlLoginRoute
  '/control/': typeof AuthenticatedControlIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/control/cases/$id': typeof AuthenticatedControlCasesIdRoute
  '/control/cases/': typeof AuthenticatedControlCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/control/login': typeof ControlLoginRoute
  '/control': typeof AuthenticatedControlIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/control/cases/$id': typeof AuthenticatedControlCasesIdRoute
  '/control/cases': typeof AuthenticatedControlCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/control': typeof AuthenticatedControlRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/control/login': typeof ControlLoginRoute
  '/_authenticated/control/': typeof AuthenticatedControlIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/control/cases/$id': typeof AuthenticatedControlCasesIdRoute
  '/_authenticated/control/cases/': typeof AuthenticatedControlCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/control'
    | '/portal'
    | '/control/login'
    | '/control/'
    | '/portal/'
    | '/control/cases/$id'
    | '/control/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/control/login'
    | '/control'
    | '/portal'
    | '/control/cases/$id'
    | '/control/cases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/control'
    | '/_authenticated/portal'
    | '/control/login'
    | '/_authenticated/control/'
    | '/_authenticated/portal/'
    | '/_authenticated/control/cases/$id'
    | '/_authenticated/control/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ControlLoginRoute: typeof ControlLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/login': {
      id: '/control/login'
      path: '/control/login'
      fullPath: '/control/login'
      preLoaderRoute: typeof ControlLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control': {
      id: '/_authenticated/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof AuthenticatedControlRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/control/': {
      id: '/_authenticated/control/'
      path: '/'
      fullPath: '/control/'
      preLoaderRoute: typeof AuthenticatedControlIndexRouteImport
      parentRoute: typeof AuthenticatedControlRouteRoute
    }
    '/_authenticated/control/cases/': {
      id: '/_authenticated/control/cases/'
      path: '/cases'
      fullPath: '/control/cases/'
      preLoaderRoute: typeof AuthenticatedControlCasesIndexRouteImport
      parentRoute: typeof AuthenticatedControlRouteRoute
    }
    '/_authenticated/control/cases/$id': {
      id: '/_authenticated/control/cases/$id'
      path: '/cases/$id'
      fullPath: '/control/cases/$id'
      preLoaderRoute: typeof AuthenticatedControlCasesIdRouteImport
      parentRoute: typeof AuthenticatedControlRouteRoute
    }
  }
}

interface AuthenticatedControlRouteRouteChildren {
  AuthenticatedControlIndexRoute: typeof AuthenticatedControlIndexRoute
  AuthenticatedControlCasesIdRoute: typeof AuthenticatedControlCasesIdRoute
  AuthenticatedControlCasesIndexRoute: typeof AuthenticatedControlCasesIndexRoute
}

const AuthenticatedControlRouteRouteChildren: AuthenticatedControlRouteRouteChildren =
  {
    AuthenticatedControlIndexRoute: AuthenticatedControlIndexRoute,
    AuthenticatedControlCasesIdRoute: AuthenticatedControlCasesIdRoute,
    AuthenticatedControlCasesIndexRoute: AuthenticatedControlCasesIndexRoute,
  }

const AuthenticatedControlRouteRouteWithChildren =
  AuthenticatedControlRouteRoute._addFileChildren(
    AuthenticatedControlRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedControlRouteRoute: typeof AuthenticatedControlRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedControlRouteRoute: AuthenticatedControlRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ControlLoginRoute: ControlLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
